export enum HttpCode {
  // Successful
  HTTP_OK = 200,

  HTTP_CREATED = 201,

  HTTP_ACCEPTED = 202,

  HTTP_NON_AUTHORITATIVE_INFORMATION = 203,

  HTTP_NO_CONTENT = 204,

  HTTP_RESET_CONTENT = 205,

  HTTP_PARTIAL_CONTENT = 206,

  // CLIENT ERRORS
  HTTP_BAD_REQUEST = 400,

  HTTP_UNAUTHORIZED = 401,

  HTTP_PAYMENT_REQUIRED = 402,

  HTTP_FORBIDDEN = 403,

  HTTP_NOT_FOUND = 404,

  HTTP_METHOD_NOT_ALLOWED = 405,

  HTTP_NOT_ACCEPTABLE = 406,

  HTTP_CONFLICT = 409,

  HTTP_UNPROCESSABLE_ENTITY = 422,

  HTTP_NOT_MODIFIED = 304,

  // SERVER ERRORS
  HTTP_INTERNAL_SERVER_ERROR = 500,

  HTTP_NOT_IMPLEMENTED = 501,

  HTTP_BAD_GATEWAY = 502,

  HTTP_SERVICE_UNAVAILABLE = 503,

  HTTP_GATEWAY_TIMEOUT = 504,

  HTTP_VERSION_NOT_SUPPORTED = 505,
}
